dbos-inc/dbos-transact-golang

dbos/dbos.go
dbos/dbos_test.go
dbos/serialization_test.go
dbos/system_database.go
dbos/workflow.go
dbos/workflows_test.go

- Allow standalone `Send()` and `SetEvent()`
- Hash executable for standalone versioning
- Automatically register `time.Time` for `encoding/gob`
- Make `Send` and `SetEvent` generic so we can register the message type with `encoding/gob` automatically

Send outside of workflows + send/set message type registration

---

dbos/admin_server_test.go
dbos/dbos.go
dbos/dbos_test.go
dbos/logger_test.go
dbos/queue.go
dbos/queues_test.go
dbos/recovery.go
dbos/system_database.go
dbos/utils_test.go
dbos/workflow.go
dbos/workflows_test.go

**Design**
This PR brings native Go cancellation facilities to workflows. Users can set a timeout, using `WithTimeout`, to a `DBOSContext` passed to `RunAsWorkflow`.
When the context is cancelled (either due to a timeout or a manual cancellation), DBOS cancellation logic (cancel the workflow in Postgres) will be triggered.
When the workflow runs or is enqueued for the first time, the deadline will be persisted in Postgres.
During recovery, we will recompute the deadline from the value stored in the database and configure the workflow context accordingly.
Details:
- Inside `RunAsWorkflow`, we create an uncancellable context to run DBOS operations and configure the handler. This allows the timeout to apply only to the user function and provide an ergonomic behavior with the handle. (The …

Workflow timeouts

---

README.md
dbos/dbos.go
dbos/errors.go
dbos/queue.go
dbos/queues_test.go
dbos/recovery.go
dbos/serialization_test.go
dbos/system_database.go
dbos/utils_test.go
dbos/workflow.go
dbos/workflows_test.go

- Make system DB private
- Update README
- Add docs for https://pkg.go.dev/github.com/dbos-inc/dbos-transact-go

Readme and docs

---

dbos/client_test.go
dbos/dbos.go
dbos/queue.go
dbos/recovery.go
dbos/serialization_test.go
dbos/system_database.go
dbos/workflow.go
dbos/workflows_test.go

This PR adds workflow management features usable by a "client context", that is, a DBOSContext object that is initialized but not launched. The benefits of doing so is being able to interact with DBOS workflows without having the process dequeue tasks, recover workflows, or run an admin server.
Features added:
- Resume workflow
- Fork workflow
- Enqueue workflow by name
- Add ability to dismiss output/input from list workflows
Because the registry is indexed by workflow FQN, we need to keep another map from workflow "custom" name to workflow FQN. This should have been tested in PR that added custom workflow names.

DBOS "client context"

---

dbos/dbos.go
dbos/workflow.go
dbos/workflows_test.go

Our current method for capturing the reflection name of a step is flawed. The typed erase function (anonymous) always has the same name, and thus every call to RunAsStep overwrites it. This of course results in wrong data in the `operation_results` table.
There is no good way to associated a unique key that the interface method can use on this map. Hence, let's just move to the cleaner functional options interface to handle step options, voiding the need for the in-memory map.
Added a test (`TestSteps/checkStepName`) that fails without this change.

Functional options for steps

---

README.md
dbos/admin_server.go
dbos/dbos.go
dbos/serialization_test.go
dbos/system_database.go
dbos/workflow.go
dbos/workflows_test.go

- Flatten send and set event inputs
- Simplify get /recv inputs
- Fix Sleep and Cancel interface signature to accept the context and match the package level methods ( 😢 )

flatten send and set event arguments

---

CONTRIBUTING.md
README.md
dbos/admin_server.go
dbos/admin_server_test.go
dbos/client_test.go
dbos/dbos.go
dbos/logger_test.go
dbos/utils_test.go
dbos/workflow.go

- Add `CONTRIBUTING.md`
- Add licence badge in `README.md`
- Privatize a few types
- Fix package level `RetrieveWorkflow` (now calls interface `RetrieveWorkflow`) 
- Few type casting checks & a fix (in `RunAsWorkflow` we shouldn't cast to the concrete type)
- Clean up all options names and visibility (option structs are public, fields are private. Harmonize names across the board)

Contributing

---

go.mod

Go offers a module proxy which, by default, keeps for ever every version it ever cached.
We need to add a `retract` directive in our `go.mod` to exclude these. See
- https://proxy.golang.org/
- https://go.dev/ref/mod#go-mod-file-retract
Here's the list the proxy knows
```
curl https://proxy.golang.org/github.com/dbos-inc/dbos-transact-go/@v/list
v1.0.0-alpha.3
v0.5.0-alpha
v0.5.1-alpha
v1.0.0-alpha4
```

retract v1s

---

dbos/admin_server.go
dbos/admin_server_test.go
dbos/client_test.go
dbos/queue.go
dbos/queues_test.go
dbos/serialization_test.go
dbos/system_database.go
dbos/utils_test.go
dbos/workflow.go
dbos/workflows_test.go

- `QueueOptions` made public
- More comprehensive recovery test (recovers more workflows and check steps status)
- Check that steps return a cancelled error after the workflow was cancelled
- Admin server:
- Always "stringify" non nil workflow output/input
- Filter out queue tasks by status (pending/enqueued) on the list queues endpoint
- Have `RetrieveWorkflow` return a handle interface

More tests and admin server fixes

---

dbos/system_database.go
dbos/workflows_test.go

In a similar plot twist, a workflow that has been cancelled can return without an error, and the current logic will update its status to success. This PR further prevents `updateWorkflowOutcome` to transition from `CANCELLED` to `SUCCESS`.

prevent cancel to success trnsitions

---

dbos/admin_server_test.go
dbos/dbos.go

Replaced hard-coded port `3001` with a configurable `AdminServerPort` field in `Config`.  
Updated `dbos.go` to use the provided port (defaulting to 3001) and adjusted tests to use a custom port (`38081`).  
✅ All `TestAdminServer` cases now pass.

Admin server port

---

dbos/admin_server.go
dbos/conductor.go
dbos/conductor_protocol.go
dbos/dbos.go
dbos/migrations/000001_initial_dbos_schema.up.sql
dbos/queues_test.go
dbos/serialization_test.go
dbos/system_database.go
dbos/workflow.go
dbos/workflows_test.go

- Expose a public `GetWorkflowSteps` function
- Move internal queue creation at launch of the context
- Skip the dequeue query if `maxTasks` <= 0
- Make db migrations idempotent

public GetWorkflowSteps

---

cmd/dbos/cli_integration_test.go
cmd/dbos/postgres.go

- The CLI test can now use the latest golang SDK (had to specifically get a version with the new migration scheme before)
- Update a log info telling users to use `postgresql` instead of `postgres` as the db driver

Remove temp install

---

cmd/dbos/migrate.go
cmd/dbos/utils.go
cmd/dbos/workflow.go
dbos/dbos.go

Update: Accept user-provided context.Context to build DBOSContext

---

dbos/system_database.go
dbos/workflows_test.go

- Fix a bug where sleep steps ID were not always generated when `recv`/`getEvent` skipped sleeping (e.g., a value was already found, during recovery)
- Fix a bug were `recv` would return an error if it recorded a timeout value
- Handle context cancellation during `recv` (addresses #86)

Fix comms durable sleeps

---

dbos/dbos.go
dbos/dbos_test.go
dbos/system_database.go

Fix: Accept custom pgxpool

---

dbos/dbos_test.go
dbos/system_database.go
dbos/utils_test.go

This PR:
- Ensure we use the user pgxpool for every interaction with the system DB, if provided
- Moves the notification listener to using a connection from from said pool, rather than using a standalone connection
- Make the notification listener loop resilient to connection failures (addresses #94)
Note that `OnNotification` has to be set before a connection is started (which is too late once Acquired from the pool), which is why the logic to handle notifications is now inlined in the listener.

use custom pool for everything in systemp db

---

dbos/system_database.go

Split schema existence check and creation.

split CREATE SCHEMA IF NOT EXISTS query

---

dbos/system_database.go
dbos/workflow.go
dbos/workflows_test.go

If a workflow observes the returned error is a `DBOSError` with code `ConflictingIDError`, fall back to `awaitWorkflowResult` in the workflow goroutine.
Note that we cannot distinguish this error if the user handles it (e.g., during `setEvent`) and wraps it with some other error message.

Handle conflicting executions

---

dbos/system_database.go

[Issue](https://github.com/dbos-inc/dbos-transact-golang/issues/84)
The system database was using a single shared notificationsMap to handle both workflow notifications (`_DBOS_NOTIFICATIONS_CHANNEL`) and workflow events (`_DBOS_WORKFLOW_EVENTS_CHANNEL`). This design could lead to potential conflicts when both channels used the same payload format (`workflowID::topic`), causing notifications intended for one channel to incorrectly trigger listeners on the other channel.
Split the single notificationsMap into two separate maps:
`workflowNotificationsMap` - dedicated to handling workflow notifications
`workflowEventsMap` - dedicated to handling workflow events

[Fix] Conflict notifications map
